### ISSUE TITLE
Change the navigation dropdown menu to mouseover

### ISSUE THREAD

**Issue by jammaymay** [Evavic44/responsive-navbar-with-dropdown#2]
Hi, I would like to check if it is possible to add CSS to modify the behavior of the desktop dropdown menu to show/hide on mouseover.

**Comment by Evavic44** [comment]
Yes, you can. Although no changes to the CSS is required. Simply replace the `click` event attached to the dropdown button with `mouseover` and make provisions for collapsing the menu on `mouseleave`.
